### ISSUE TITLE
bip-tapscript: behavior of empty signatures isn't clear

### ISSUE THREAD

**Issue by sipa** [sipa/bips#101]
Review comment by @gmaxwell.

Some of the text can be misinterpreted to mean that empty signatures cause an abort of the script.

(on mobile currently, i'll edit later to show the exact section)

**Comment by sipa** [comment]
@gmaxwell Care to elaborate a bit on this?

**Comment by gmaxwell** [comment]
"If the signature is not the empty vector, the signature is validated according to the bip-taproot signing validation rules against the public key and the tapscript transaction digest (to be defined hereinafter) as message. Validation failure MUST cause the script to fail and terminate immediately."  < this sounds like the empty vector will terminate.

**Comment by sipa** [comment]
Does #186 improve upon this?
