### ISSUE TITLE
bip-schnorr: clarify rationale  for key prefixing

### ISSUE THREAD

**Issue by real-or-random** [sipa/bips#106]
I find the paragraph about  key prefixing and BIP32 is slightly confusing. It should separate these two concerns more clearly:
1. committing to the public key is necessary for security in many advanced advanced key generation methods, e.g., BIP32, MuSig, ...
2. transaction signatures in bitcoin currently on the key but we don't want to rely on this.

**Comment by sipa** [comment]
Sounds good.

**Comment by real-or-random** [comment]
I'll give it a try.
