### ISSUE TITLE
bip-schnorr: non-malleability is not an advantage over ECDSA

### ISSUE THREAD

**Issue by real-or-random** [sipa/bips#107]
ECDSA as currently used is already non-malleable. See also
https://nbn-resolving.de/urn:nbn:de:hbz:294-60803

**Comment by sipa** [comment]
Low S is only a standardness rule on the network, though. I guess we could say something like "When ECDSA is restricted to having an s value in the lower half of the range (as is currently done in Bitcoin by common policy rules), it can be proven non-malleable, but again under stronger assumptions than needed to prove Schnorr signatures non-malleable."?

**Comment by elichai** [comment]
arghh. I think this is a bitcoin improvement proposal. meaning it should focus on bitcoin and not a theoretical paper.
this is also why you wrote about 72 bytes, even though ECDSA can be 64 bytes. but in bitcoin they're currently 72 bytes.

**Comment by sipa** [comment]
@elichai I don't know what point you're making.

**Comment by elichai** [comment]
Right. It just feels like the document is already kinda bloated, especially for non-cryptographers. so I would personally prefer if you just use softer words on the malleability instead of expanding on the possibility of making ECDSA non-malleable.

**Comment by sipa** [comment]
It is not about making ECDSA non-malleable. Under these assumptions, ECDSA, as currently used in Bitcoin, is non-malleable.

**Comment by elichai** [comment]
policy, not consensus. but nvm

**Comment by sipa** [comment]
Sure, but we're claiming in the section about advantages of Schnorr over ECDSA that Schnorr is provably non-malleable while ECDSA is not.

One resolution is moving the non-malleability claim to the "independent of the actual signature scheme" section, which is true - we can make ECDSA non-malleable in a much simpler way than introducing Schnorr.

Another option is to leave it as is, but weaken it from "no proof" to "prove under stronger assumptions, and with low s". Given that that is what is de facto used, that seems preferable to me.

**Comment by elichai** [comment]
That sounds good. sorry didn't want to sound pedantic just adding a sentence like

> When ECDSA is restricted to having an s value in the lower half of the range (as is currently done in Bitcoin by common policy rules), it can be proven non-malleable, but again under stronger assumptions than needed to prove Schnorr signatures non-malleable.

Is a bit much.

**Comment by real-or-random** [comment]
To be honest, when I opened this issue, I missed that low-S is not a consensus rule. But what @sipa says in the previous post makes sense.

**Comment by gmaxwell** [comment]
I believe the BIP's claims are overly strong in another way too "Non-malleability: The SUF-CMA security of schnorr signatures implies that they are non-malleable."   SUF-CMA of an abstract scheme doesn't mean any concrete protocol / implementation is non-malleable.  So, for example, EdDsa is an r,s schnorr signature like this BIP, but actual implementations are vulnerable to malleability in practice!

**Comment by sipa** [comment]
@gmaxwell That's a good point, but I don't know to address it. In that section of the text we're not yet instantiating the exact scheme, but discussing the abstract advantages Schnorr has over ECDSA, and in that context I think it's fair to say that yes, Schnorr at least theoretically can be proven non-malleable. Perhaps that statement needs to be repeated as a concrete design goal, so that we can later show that not only does the scheme abstractly permit non-malleability, but the concrete scheme is designed to not break that property.

**Comment by gmaxwell** [comment]
I think the value of stating the objectives is largely so that people can review it and say "no it doesn't do that, consider this case", or to make it clear why it did this instead of that.   For neither of those purposes is it helpful to make some strongly worded argument that the property was actually delivered.

So stating concrete objectives, and tying design features to those objectives is good.   Stating abstract properties as proof an objective is met is not, because they don't actually do that.

**Comment by sipa** [comment]
Sure, but the point of the initial section isn't to prove the scheme we're proposing has this property. It's justifying the choice of the (abstract) Schnorr algorithm over ECDSA as a basis to build the spec on. I think it's perfectly fitting in that context to show a proof exists.

**Comment by real-or-random** [comment]
I'll try to reword this. Sure, it would be naive to say that the abstract security directly implies that the scheme in this spec is non-malleable, and this is not what we wanted to say. But our goal is to specify a solid practical scheme, so we build it on solid theoretical foundations.

I think there are two things to this:
 - We want a non-malleable abstract scheme; otherwise we have have no change of specifying a non-malleable concrete scheme. And the fact that multiple groups of researchers wrote security proofs for non-malleability of the abstract scheme gives us good confidence.
 - A goal of the spec is to specify a concrete non-malleable scheme.

In footnote 2 of the current draft, we spend some sentences on arguing why the differences between the abstract schemes assumed for the proof and the concrete scheme do not matter. We could expand this by adding stuff like "we use unique encodings into bytearrays" and "the order of the arguments in the hash function does not matter" but I don't think that these arguments add much for people who are able to understand the currently given arguments. 

By the way, I don't believe in fundamental differences between the security of an abstract scheme and the security of a concrete scheme. It's really a question of how close your abstract model is to reality. EdDSA is a great example here.

First let's look at the paper: It's good that it specifies the scheme including the bit representation of everything; the EdDSA algorithms take bitstrings and output bitstrings. It's maybe not so good that some other choices are left the implementation

And second, the reason why EdDSA is malleable even though EdDSA is an Schnorr signature like this BIP is that in fact it's not a Schnorr signature as in the papers that we refer to: In the papers, s is an group element, which must be encoded uniquely into bytearrays, and not an integer, which could be "high". Sometimes the assumption that s is an element of Z_p (or Z*_p, another interesting detail) is written down explicitly -- and sometimes it's just implicit, which arguably lacks rigor: if one is trying to prove strong unforgeability then one should at least be explicit about the details that matter.

**Comment by sipa** [comment]
There are a number of general points here that can be addressed, but back to the issue topic: I think we should just add a footnote to the non-malleability bulletpoint that if we take the modified ECDSA scheme into account that is used on the network today, there actually does exist a proof for non-malleabity under nonstandard assumptions.
