### ISSUE TITLE
bip-taproot: Add security argument

### ISSUE THREAD

**Issue by jonasnick** [sipa/bips#119]
As far as I can see, the taproot bip currently lacks any discussion about why the taproot construction is secure. There's @apoelstra's [security proof](https://github.com/apoelstra/taproot) which we could link to. The paper itself could be expanded (introduction) and clarified a bit. I'm having troubles figuring out what properties are proven and what is missing every time I look at it.

**Comment by gmaxwell** [comment]
"Proving the security of this construction is left for an exercise for the reader." :P

**Comment by sipa** [comment]
@real-or-random and I were discussing some properties we'd like to see proven before. But for now I think it makes sense to link to what we have in the document.

**Comment by AdamISZ** [comment]
@gmaxwell sure, for key path spending. For script path spending I didn't find it obvious, because it's not a collision on a hash function like p2sh is (which seems relevant as you principally want to reduce to existing security assumptions; that's even mentioned in the BIP design/motivation).

**Comment by sipa** [comment]
See #181 which adds a link to @apoelstra's proof.

**Comment by sipa** [comment]
I believe this is fixed by #181.
