### ISSUE TITLE
Diagram under "Constructing and spending Taproot outputs" doesn't show

### ISSUE THREAD

**Issue by bjarnemagnussen** [sipa/bips#139]
The image under "Constructing and spending Taproot outputs" is unfortunately(!) broken.

It is probably a Github issue as it shows with a SSL certificate issue. But even doing `wget https://raw.githubusercontent.com/sipa/bips/bip-schnorr/bip-taproot/tree.png --no-check-certificate` gives a 404 error.

Maybe it can be fixed with a re-upload?

**Comment by ajtowns** [comment]
This seems to work fine for me?

**Comment by bjarnemagnussen** [comment]
Seems to have been resolved on Githubs end? Works for me again too!
