### ISSUE TITLE
bip-schnorr: Inaccurate proof of quadratic residuosity

### ISSUE THREAD

**Issue by hebasto** [sipa/bips#159]
From footnote 9:
> Given a candidate _x_, the valid _Y_ coordinates are the square roots of _c = x<sup>3</sup> + 7 mod p_ and they can be computed as _y = ±c<sup>(p+1)/4</sup> mod p_ (see Quadratic residue) if they exist, which can be checked by squaring and comparing with _c_. Due to Euler's criterion it then holds that _c<sup>(p-1)/2</sup> = 1 mod p_. The same criterion applied to _y_ results in _y<sup>(p-1)/2</sup> mod p = ±c<sup>((p+1)/4)((p-1)/2)</sup> mod p = ±1 mod p_. Therefore _y = +c<sup>(p+1)/4</sup> mod p_ is a quadratic residue and _-y mod p_ is not.

This part of equation _y<sup>(p-1)/2</sup> mod p = ±c<sup>((p+1)/4)((p-1)/2)</sup> mod p_ is not correct for the minus sign.

For the strict proof:
1. _y<sup>(p-1)/2</sup> mod p = (c<sup>(p+1)/4</sup>)<sup>(p-1)/2</sup> mod p = (c<sup>(p-1)/2</sup>)<sup>(p+1)/4</sup> mod p = 1 mod p_; therefore, every _y = +c<sup>(p+1)/4</sup> mod p_ is a quadratic residue
2. there are _(p-1)/2_ residues and _(p−1)/2_ nonresidues; therefore, every _-y = -c<sup>(p+1)/4</sup> mod p_ is not a quadratic residue

My higher education was not in English, so I kindly ask anyone with good academic English to make a PR.

**Comment by jonasnick** [comment]
I fail to see why the existing proof is incorrect but I totally agree that this section needs to be reworked. For one, it needs to be stated what exactly is proven.

To prove: c mod p is a QR => y = b*c<sup>(p+1)/4</sup> mod p is a QR for b = 1 and a non-QR for b = -1

It holds that (-1)<sup>(p-1)/2</sup> = -1 because p = 3 mod 4 which implies (p - 1)/2 = 1 mod 2.

For b in {-1, 1} we have

y<sup>(p-1)/2</sup> mod p
 = (b*c<sup>(p+1)/4</sup>)<sup>(p-1)/2</sup> mod p
                          = b<sup>(p-1)/2</sup> * (c<sup>(p-1)/2</sup>)<sup>(p+1)/4</sup> mod p
                          = b * 1<sup>(p+1)/4</sup> mod p
                          = b mod p

If that convinces you, I can open a PR to improve the section.

**Comment by hebasto** [comment]
@jonasnick 
> I fail to see why the existing proof is incorrect...

I didn't mean "incorrect", rather "inaccurate" or "loose" ;)

> It holds that (-1)<sup>(p-1)/2</sup> = -1 because p = 3 mod 4 which implies (p - 1)/2 = 1 mod 2.

Correct. But I'd prefer do not use modular operations with an exponent:

[1] for secp256k1 it holds that _p = 3 mod 4_ or _p = 4k+3_
[2]  _(-1)<sup>(p-1)/2</sup> mod p = (p-1)<sup>(2k+1)</sup> mod p =
=(p<sup>2</sup>-2p+1)<sup>k</sup> * (p-1) mod p = 1<sup>k</sup> * (p-1) mod p = -1 mod p_ 

> ... I can open a PR to improve the section.

It will be very kind of you.
